<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-21T23:01:52 ICT" name="Surefire suite" finished-at="2023-12-21T23:05:19 ICT" duration-ms="206558">
    <groups>
    </groups>
    <test started-at="2023-12-21T23:01:52 ICT" name="Surefire test" finished-at="2023-12-21T23:05:19 ICT" duration-ms="206558">
      <class name="Edx.com.testcases.EdxTest">
        <test-method is-config="true" signature="BeginWebTest()[pri:0, instance:Edx.com.testcases.EdxTest@61eaec38]" started-at="2023-12-21T23:01:52 ICT" name="BeginWebTest" finished-at="2023-12-21T23:01:54 ICT" duration-ms="2241" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeginWebTest -->
        <test-method signature="EdxAutomation()[pri:0, instance:Edx.com.testcases.EdxTest@61eaec38]" started-at="2023-12-21T23:01:54 ICT" name="EdxAutomation" finished-at="2023-12-21T23:04:41 ICT" duration-ms="166957" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EdxAutomation -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:Edx.com.testcases.EdxTest@61eaec38]" started-at="2023-12-21T23:04:42 ICT" name="closeDriver" finished-at="2023-12-21T23:04:42 ICT" duration-ms="649" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
        <test-method is-config="true" signature="BeginWebTest()[pri:0, instance:Edx.com.testcases.EdxTest@61eaec38]" started-at="2023-12-21T23:04:42 ICT" name="BeginWebTest" finished-at="2023-12-21T23:04:43 ICT" duration-ms="1060" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeginWebTest -->
        <test-method signature="failTC()[pri:0, instance:Edx.com.testcases.EdxTest@61eaec38]" started-at="2023-12-21T23:04:43 ICT" name="failTC" finished-at="2023-12-21T23:05:18 ICT" duration-ms="34416" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Element not exist. By.name: audit_mode]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Element not exist. By.name: audit_mode
at org.testng.Assert.fail(Assert.java:110)
at selenium4.com.helpers.WebElementsHelpers.waitForElementPresent(WebElementsHelpers.java:2547)
at selenium4.com.helpers.WebElementsHelpers.waitForElementVisible(WebElementsHelpers.java:2450)
at selenium4.com.helpers.WebElementsHelpers.clickElement(WebElementsHelpers.java:2121)
at Edx.com.pages.EdxLoginPage.clickContinueButton(EdxLoginPage.java:99)
at Edx.com.pages.EdxLoginPage.LoginToEdx(EdxLoginPage.java:94)
at Edx.com.pages.EdxLoginPage.takeAction(EdxLoginPage.java:40)
at Edx.com.testcases.EdxTest.failTC(EdxTest.java:61)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failTC -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:Edx.com.testcases.EdxTest@61eaec38]" started-at="2023-12-21T23:05:18 ICT" name="closeDriver" finished-at="2023-12-21T23:05:19 ICT" duration-ms="479" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- Edx.com.testcases.EdxTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
